### ISSUE TITLE
Impossible to install picsimlab on debain 12 with latest .deb

### ISSUE THREAD

**Issue by Integrat-edCircuit** [lcgamboa/picsimlab#103]
It is impossible to install picsimlab since apt/dpkg on debian 12 cannot find  libwxbase3.0-0v5 (>= 3.0.4+dfsg) and libwxgtk3.0-gtk3-0v5 (>= 3.0.4+dfsg-10~). The packages do exists as part of the [wxwidget](https://tracker.debian.org/pkg/wxwidgets3.2l) package on the debian repos.

1. Download .deb release
2. Install it with apt/dpkg
3. enter 'y' key to launch install

PICsimlab installs itselfs.

![image](https://github.com/lcgamboa/picsimlab/assets/136177157/ae6e15da-be7d-4351-b434-f57effbf7b80)

OS:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

**Comment by lcgamboa** [comment]
Hi @Integrat-edCircuit ,

the .deb package is for Ubuntu 20.04.6 LTS, unfortunately I am unable to make packages for all distros. The AppImage or flatpak version is more universal and should work without problems. I am personally a Debian user.

I made a[ .deb using Debian Test](https://github.com/lcgamboa/picsimlab/releases/download/latestbuild/picsimlab_0.9.1-1_amd64_Debian_Test.deb) if you want to test.

**Comment by lcgamboa** [comment]
I used docker to create a package for [Debian stable](https://github.com/lcgamboa/picsimlab/releases/download/latestbuild/PICSimLab_0.9.2_240210_Debian_GNU_Linux_12_.bookworm._amd64.deb). See if the installation now works.
