### ISSUE TITLE
Gpboard simulation failed

### ISSUE THREAD

**Issue by Kabak85** [lcgamboa/picsimlab#106]
Tried with 12F675 on Gpboard on picsimlab 0.9.1 Win64 (Windows 7 64).

When using an HEX where OSCCAL is not set ( value 0x3FFF) and the internal oscillator, the simulation seems not running.

The OSCCAL value is set at programming by reading the original value from PIC and rewrite it.  The simulator MUST verify and replace it, if necessary, by a valid value ( 0x3400 to 0x34FF ) when loaded.

Not tested on others boards or other pic.

**Comment by Kabak85** [comment]
gpsim 0.32 had the issue too.

I made a ticket about it at the same time : https://sourceforge.net/p/gpsim/bugs/292/

**Comment by lcgamboa** [comment]
As soon as I have time I will update PICSimLab to use the newest version of gpsim.

**Comment by lcgamboa** [comment]
The [last unstable version](https://github.com/lcgamboa/picsimlab/releases/tag/latestbuild) was updated to use gpsim 0.32.1.

**Comment by Kabak85** [comment]
Hi @lcgamboa

I confirm it solve the OSCCAL issue.

Thanks.
