### ISSUE TITLE
Blue Pill Board Wrong schematics 

### ISSUE THREAD

**Issue by godsi** [lcgamboa/picsimlab#118]
Hello,

I am currently using version 0.9.2 of PICSimLab (PICSimLab_0.9.2_240803_win64), and I recently encountered an issue while testing the BLUE PILL. It seems there might be a discrepancy between the schematics and the actual circuit.

I am currently programming using registers. According to the schematics, when PC13 is set to LOW, the LED should light up. However, after setting PC13 to LOW in the program, the LED did not light up. I tried setting PC13 to HIGH, and unexpectedly, the LED light up. Could it be that there's an internal circuit error? Below are my code and the results.

Thank you for your help.
![螢幕擷取畫面 2024-08-16 170030](https://github.com/user-attachments/assets/f3e88ccf-3d98-480e-b4fd-abcbe6db4fb7)
![螢幕擷取畫面 2024-08-16 170107](https://github.com/user-attachments/assets/ca9b2e0a-d7d2-47dc-b3f2-65791d870cd7)
![螢幕擷取畫面 2024-08-16 170136](https://github.com/user-attachments/assets/7949010c-bd27-4811-b8ff-38f5baeee4f7)
![螢幕擷取畫面 2024-08-16 170414](https://github.com/user-attachments/assets/e67e4a70-1c9d-4006-b564-01acf22580b4)

**Comment by lcgamboa** [comment]
You are correct, the implementation in the simulator had the polarity reversed. 
The correction was made in commit 1346954. 
[Version 0.9.2_240818](https://github.com/lcgamboa/picsimlab/releases/tag/latestbuild) already contains the changes. 
Thanks for reporting the problem.

**Comment by godsi** [comment]
Hi @lcgamboa 

I downloaded the latest version, and its work fine

Thanks
