### ISSUE TITLE
LCD1602 working with x board but not working with gpboard using PIC16F877A

### ISSUE THREAD

**Issue by eagl1** [lcgamboa/picsimlab#127]
Hi,

I used the same code and same pin configuration. But it's working with x board but not working with gpboard, here are the photos:

1. gpboard:

![image](https://github.com/user-attachments/assets/66cecf06-7a8c-4719-825a-9203307579f8)

2. x board:

![image](https://github.com/user-attachments/assets/96e620c5-5786-474f-bb5d-6be519a6a92a)

What could be the problem ? I think it's a bug with the gpboard.

**Comment by lcgamboa** [comment]
Hi @eagl1,

Could you share the source code and the workspace file (.pzw)? It is probably some problem with the gpsim interface with PICSimLab.

**Comment by eagl1** [comment]
[code_simulation.zip](https://github.com/user-attachments/files/17350363/code_simulation.zip)

**Comment by lcgamboa** [comment]
Hi @eagl1, in your code you don't initialize the `ADCON1` register. After reset the `ADCON1 = 0` and all ADC input pins are in analog mode (including the REx pins). Initializing the `ADCON=0x06` put all pins  in digital mode and solve the problem. In the real (and PICSimlab) PIC microcontroller if the pin is configured as output in analog mode it work (but consumes more energy and it is not recommended by datasheet), but it don't work with gpsim.
