### ISSUE TITLE
ili9341 with "spi+touch" crashes simulator or causes infinite loop

### ISSUE THREAD

**Issue by m-meltner** [lcgamboa/picsimlab#131]
Hello,

Describe the bug:
simulator crashes or is in infinite loop

- create a default project
- add the ili9341
- switch it to mode "spi+touch" without actually assigning any pins (if reasonable pin numbers are assigned the behaviour in the same)
- press "ok" in the dialog box
- crash or infinite loop

Expected behavior:
dialog box closes and simulator continues

Files:
a default project as starting point is enough

Desktop (please complete the following information):
all versions including online simulator

Possible fix:
if I comment out lines 620 & 621 in "output_LCD_ili9341.cc" ("SpareParts.WPropCmd("combo11", PWA_COMBOGETTEXT, NULL, buff);")
the simulator works fine. these 2 lines look like a copy-paste error in the source code to me though I am not deep enough into the simulator source code to be sure.

    Michael

**Comment by lcgamboa** [comment]
Hi @m-meltner ,

Thanks for reporting the issue and providing the fix. You are right about the problem with these two lines.

**Comment by m-meltner** [comment]
Hello,

thanks for confirming and big smile from me for your effort providing picsimlab!

Michael
