### ISSUE TITLE
Picsimlab 0.92, not communicating with MPLAB X

### ISSUE THREAD

**Issue by Arto1234** [lcgamboa/picsimlab#132]
My system:
- Ubuntu 22.04.1 LTS 64 bit (6.8.0-49-generic)
- Picsimlab 0.92
- Board in Picsimlab is Mclab2 PIC16F877A
- tty0tty is loaded, checked with lsmod, but nobody is using it

Picsimlab config: serial port: /dev/tnt2
What may be wrong?

**Comment by Arto1234** [comment]
tty0tty version is 1.4

**Comment by lcgamboa** [comment]
Hi @Arto1234 ,
It is not necessary to configure tty0tty to communicate with MPLABX. tty0tty is for serial communication, if the objective is only to view the information sent by the serial port, it is simpler to use the spare part [Virtual Term](https://lcgamboa.github.io/picsimlab_docs/stable/IOVirtualTerm.html). To communicate with MPLABX it is necessary to install a [plugin](https://github.com/lcgamboa/picsimlab/releases/download/v0.9.2/com-picsim-picsimlab.nbm). The MPLABX debug plugin (com-picsim-picsimlab.nbm) don't work with MPLABX versions greater than 6.05

**Comment by Arto1234** [comment]
Thanks for info, so quickly! :) Is fix coming in near future? I started to use MPLAB X 6.20...

**Comment by lcgamboa** [comment]
As soon as Microchip updates your documentation.  See https://github.com/lcgamboa/picsimlab/discussions/124

**Comment by Arto1234** [comment]
Thank you. So until then we have to use version 6.05.
I'll close this.
(I'd like to have your comment on another topic: 
What do you think, how big effort is to add simulation support for e.g. SAMV71 eval board?)

**Comment by lcgamboa** [comment]
The SAMV71 is a very complex device. Using the Qemu arm, it is possible to emulate the CPU, but the peripherals would all have to be implemented, which would take a lot of time.
