### ISSUE TITLE
i2c.c missing port redirection

### ISSUE THREAD

**Issue by Amr-MKamal** [lcgamboa/picsimlab#15]
https://github.com/lcgamboa/picsimlab/blob/master/docs/examples/board_4/PIC18F4550/test_b4/src/test_b4.X/i2c.c
TRISC=0x01; needs to move from main to a i2c_init

**Comment by lcgamboa** [comment]
The picsimlab examples are moved to other repo: https://github.com/lcgamboa/picsimlab_examples
The pic examples source code are outdated, I have new versions, but no time to update.
Thank you for your help.
