### ISSUE TITLE
PIC16F1788 simulation missing AN11 / AN12 /AN13 ?

### ISSUE THREAD

**Issue by cdjoubert** [lcgamboa/picsimlab#19]
Hi,
PicSimLb is a very nice project, thanks for the good work.
I am trying to port a small board we use with our students. The MCU is a PIC16F1788. One of the ADC does not work : it's AN12, on pin 21. I had a look into PIC16F1788.c, and I think some lines are missing in function PIC16F1788_reset() : 

 pic->adc[0] = 2; 
...
pic->adc[10] = 22; // OK
pic->adc[11] = 25; // Missing ?
pic->adc[12] = 21; // Missing ?
pic->adc[13] = 26; // Missing ?

... and a line in PIC16F1788_start() should be corrected:  
pic->ADCCOUNT = 14;  // instead of 11

Am I right ?

Best Regards

**Comment by lcgamboa** [comment]
Yes you are right. Experimental microcontrollers still lack properties, as in this case. But this is a problem with PICsim and not with PICSimLab. Thanks for the contribution, the code has already been updated in the PICsim repository.
