### ISSUE TITLE
Build error: undefined reference to "GDB"

### ISSUE THREAD

**Issue by luizfeldmann** [lcgamboa/picsimlab#20]
Hi,
There is some problem linking to some of the functions (statically) defined in sim_gdb.c

/usr/bin/ld: boards/board_simavr.o: in function `avr_callback_run_gdb_(avr_t*)':
/home/luiz/Desktop/Sim/picsimlab/src/boards/board_simavr.cc:328: undefined reference to `gdb_watch_find'
/usr/bin/ld: /home/luiz/Desktop/Sim/picsimlab/src/boards/board_simavr.cc:335: undefined reference to `gdb_send_quick_status'
/usr/bin/ld: /home/luiz/Desktop/Sim/picsimlab/src/boards/board_simavr.cc:344: undefined reference to `gdb_network_handler'
/usr/bin/ld: boards/board_simavr.o: in function `board_simavr::DebugLoop()':
/home/luiz/Desktop/Sim/picsimlab/src/boards/board_simavr.cc:408: undefined reference to `gdb_network_handler'

**Comment by lcgamboa** [comment]
Hi Luiz,

for now PICSimLab uses a modified version of simavr of repo https://github.com/lcgamboa/simavr .
If you prefer you can build PICSimLab using the script picsimlab_build_all_and_deps.sh .
In the future I intend to use the original linux simavr library.
