### ISSUE TITLE
Is there a way to display a custom character on 16x2 LCD screen on 16F877A

### ISSUE THREAD

**Issue by wvffle** [lcgamboa/picsimlab#27]
As in the title, is there a way to do so?

I'm having hard time trying to understand how to do so using all of the available APIs in [lcgamboa/picsimlab_examples](https://github.com/lcgamboa/picsimlab_examples)

The code [(1)](https://openlabpro.com/guide/custom-character-lcd-pic/), [(2)](https://circuitdigest.com/microcontroller-projects/custom-characters-on-lcd-using-pic16f877a) I found on the internet compiles well, but doesn't seem to display anything from the CGRAM. Either I'm missing something or I simply don't quite understand the basics ;/

Can anyone explain me how to do so? It also may be a bug, hence the issue. If it turns out to be just my misunderstanding then feel free to close the issue without an answer, I won't be mad :p

**Comment by devdanzin** [comment]
@wvffle did you solve the issue? If so, can you explain what it was? Thanks!

**Comment by wvffle** [comment]
Sure thing,

To display the custom character you have to first write it to the CGRAM. You can do so by using command `lcd_cmd(0x40);` (if I remember correctly).
Then you define the character. It consists of 8x 5-bit integers, bits of value `1` are turning on respective pixels. Then go back to the line one/2 with `lcd_cmd(L_L1);` and write your characters with `lcd_dat(index);` where `index` is the index of your character. As far as I understand, you can define 8 characters at most.

So to display a simple face in first line, you'd do:

```c
lcd_cmd(0x40); // you can add 8 * index if you want to define character at index

lcd_dat(0b00000);
lcd_dat(0b00000);
lcd_dat(0b01010);
lcd_dat(0b01010);
lcd_dat(0b10001);
lcd_dat(0b01110);
lcd_dat(0b00000);
lcd_dat(0b00000);

lcd_cmd(L_L1);
lcd_dat(0);
```
