### ISSUE TITLE
Change install location

### ISSUE THREAD

**Issue by deananorth** [lcgamboa/picsimlab#39]
Is it possible to install PICSimLab on a drive other than C: using the installer for Windows?
The installer seems to provide no way of setting the install location.

**Comment by lcgamboa** [comment]
Please test this new installer version with the option to choose the install location:  https://sourceforge.net/projects/picsim/files/latest%20code%20build%20%28unstable%29/picsimlab_0.8.9_210803_win64_setup.exe/download

**Comment by deananorth** [comment]
Tested the new installer.

It seems to work as expected and installed PicSimLab where I asked. (D:\Program Files\PicsimLab)

![image](https://user-images.githubusercontent.com/59711369/128120012-964f79f6-3664-4a81-aed5-1384148b973e.png)
