### ISSUE TITLE
Board 2 - 16f648a

### ISSUE THREAD

**Issue by Anobium** [lcgamboa/picsimlab#4]
Board 2 with 16f648a - how do I make the MCLR an input?
Tried lot of options - all failed.  Or, is this a limitation of the 16f648a and you are emulating that?

**Comment by lcgamboa** [comment]
By disabling MCLR in the configuration bits, the pin can be used as input. As it is connected to the board reset circuit, it should not work properly if something is connected in parallel.
Could you describe how you are trying to use it?

**Comment by Anobium** [comment]
This program demonstrates the issue.  https://github.com/Anobium/Great-Cow-BASIC-Library-Development/blob/master/PCF8563%20Clock/PICSIMIssues/16f648a_MLCR_001.gcb

Press the MCLR button on the  board flashes the Green LED.  hold the MCLR button for longer clears the LCD.

Compile and test.

**Comment by Anobium** [comment]
Excellent

**Comment by lcgamboa** [comment]
fixed in commit 708a3fe
