### ISSUE TITLE
Compilation Error!!

### ISSUE THREAD

**Issue by sammycage** [lcgamboa/picsimlab#40]
<pre><b>picsimlab4.cc:</b> In member function ‘<b>void CPWindow4::SetSample()</b>’:
<b>picsimlab4.cc:340:4:</b> <font color="#EF2929"><b>error: </b></font>reference to ‘<b>data</b>’ is ambiguous
  340 |    <font color="#EF2929"><b>data</b></font>[fp][0][is] = -pins[0]+((1.0 * rand () / RAND_MAX) - 0.5)*0.1;
      |    <font color="#EF2929"><b>^~~~</b></font>
In file included from <b>/usr/local/include/c++/11.1.0/string:54</b>,
                 from <b>/usr/local/include/c++/11.1.0/bits/locale_classes.h:40</b>,
                 from <b>/usr/local/include/c++/11.1.0/bits/ios_base.h:41</b>,
                 from <b>/usr/local/include/c++/11.1.0/ios:42</b>,
                 from <b>/usr/local/include/c++/11.1.0/ostream:38</b>,
                 from <b>/usr/local/include/c++/11.1.0/iostream:39</b>,
                 from <b>/usr/include/lxrad/clxrad.h:52</b>,
                 from <b>/usr/include/lxrad/lxrad.h:45</b>,
                 from <b>picsimlab4.h:29</b>,
                 from <b>picsimlab4.cc:29</b>:
<b>/usr/local/include/c++/11.1.0/bits/range_access.h:319:5:</b> <font color="#34E2E2"><b>note: </b></font><b>candidates are: ‘template&lt;class _Tp&gt; constexpr const _Tp* std::data(std::initializer_list&lt;_Tp&gt;)</b>’
  319 |     <font color="#34E2E2"><b>data</b></font>(initializer_list&lt;_Tp&gt; __il) noexcept
      |     <font color="#34E2E2"><b>^~~~</b></font>
<b>/usr/local/include/c++/11.1.0/bits/range_access.h:310:5:</b> <font color="#34E2E2"><b>note: </b></font><b>                ‘template&lt;class _Tp, long unsigned int _Nm&gt; constexpr _Tp* std::data(_Tp (&amp;)[_Nm])</b>’
  310 |     <font color="#34E2E2"><b>data</b></font>(_Tp (&amp;__array)[_Nm]) noexcept
      |     <font color="#34E2E2"><b>^~~~</b></font>
<b>/usr/local/include/c++/11.1.0/bits/range_access.h:300:5:</b> <font color="#34E2E2"><b>note: </b></font><b>                ‘template&lt;class _Container&gt; constexpr decltype (__cont.data()) std::data(const _Container&amp;)</b>’
  300 |     <font color="#34E2E2"><b>data</b></font>(const _Container&amp; __cont) noexcept(noexcept(__cont.data()))
      |     <font color="#34E2E2"><b>^~~~</b></font>
<b>/usr/local/include/c++/11.1.0/bits/range_access.h:290:5:</b> <font color="#34E2E2"><b>note: </b></font><b>                ‘template&lt;class _Container&gt; constexpr decltype (__cont.data()) std::data(_Container&amp;)</b>’
  290 |     <font color="#34E2E2"><b>data</b></font>(_Container&amp; __cont) noexcept(noexcept(__cont.data()))
      |     <font color="#34E2E2"><b>^~~~</b></font>
</pre>

**Comment by sammycage** [comment]
But it compiled successfully after I changed `board` to g_board``

**Comment by lcgamboa** [comment]
Variable renamed in this commit https://github.com/lcgamboa/picsimlab/commit/cef3c146c96d467ff7967a3db62847c1567d0b9d
