### ISSUE TITLE
AppImage version doesn't launch.

### ISSUE THREAD

**Issue by ArtMiranda** [lcgamboa/picsimlab#48]
**Describe the bug**
AppImage version doesn't launch in Fedora 35
I tested it with and without AppImageLauncher.

**To Reproduce**
1. Download any AppImage version
2. Give it the permissions to run
3. Run the app

**Expected behavior**
The App runs and works as it should do.

**Screenshots**
![image](https://user-images.githubusercontent.com/50926874/143614543-daba7a48-86b0-4178-a414-4e0a320b5fa0.png)

**Desktop (please complete the following information):**
 - OS: [Fedora with GNOME]
 - Version [35]

**Comment by lcgamboa** [comment]
Apparently the Appimage format version doesn't work directly on newer Linux versions, it is necessary to specify the libgmodule library path.
try:
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so ./PICSimLab-0.8.9-x86_64.AppImage`

I have fixed this issue in continuous build version [PICSimLab-0.8.9_211123-x86_64.AppImage](https://github.com/lcgamboa/picsimlab/releases/download/latestbuild/PICSimLab-0.8.9_211123-x86_64.AppImage) check to see if this version works for you.

**Comment by ArtMiranda** [comment]
Using the new build version it launches now, but when i click to load a hex file it crashes, and if i try to launch it again it doesn't launch.

If i download the file again and try to launch it works, but it opens just once.

**Comment by lcgamboa** [comment]
Is there an error message on the console? Is the error when opening the file loading dialog or loading the file? 

Unfortunately I don't have a Fedora available to test, I do the tests on Debian and Ubuntu.

**Comment by ArtMiranda** [comment]
Here's a screenshot of when i run it at the terminal

![image](https://user-images.githubusercontent.com/50926874/143621447-017c06a9-a85d-480f-b60d-80f7fac57c8f.png)

**Comment by lcgamboa** [comment]
The AppImage format hasn't worked very well on newer versions of Linux... I'll probably use another format like Flatpak in the future. From the screenshots I can't identify what the problem would be. I'll do more research. If you want we can talk (in Portuguese) through the [Discord](https://discord.gg/fMT8szFYq7) channel later and try to solve the problem.

**Comment by ArtMiranda** [comment]
I think Flatpak would be the best way on my opinion, How can I contact on Discord?

**Comment by ArtMiranda** [comment]
I think Flatpak would be the best format, I'll contact on Discord.

**Comment by ArtMiranda** [comment]
It opens now, but there is an error, any changes in the window needs the window to "reload" (Alt+tab twice), as show in the video below.

(This program should do a binary count with the LEDS)

https://user-images.githubusercontent.com/50926874/144537118-963c849d-8d9b-4069-8944-42ec6e288dd4.mp4


Maybe this is an error with the Wayland integration, I'll do some tests on Xorg and report to you.

**Comment by ArtMiranda** [comment]
It opens now, but there is an error, any changes in the window needs the window to "reload" (Alt+tab twice), as show in the video below.

(This program should do a binary count with the LEDS)


https://user-images.githubusercontent.com/50926874/144537258-8d92fef0-d749-4305-b486-9ce93db84943.mp4


Maybe this is an error with the Wayland integration, I'll do some tests on Xorg and report to you.

**Comment by ArtMiranda** [comment]
Tested on Xorg, works perfectly.

The bugs are problems with the Wayland integration.

**Comment by lcgamboa** [comment]
The problem is in PICSimLab, apparently it only works in wayland by setting the environment variable GDK_BACKEND=x11. But I haven't been able to get this to work with flatpak yet. 
When I compile natively in ubuntu it works without problem in wayland. It's some configuration in one of the wxwidgets, gtk3 or gdk libraries.

**Comment by lcgamboa** [comment]
Can you try this command: 
`flatpak run --nosocket=wayland com.github.lcgamboa.picsimlab`

**Comment by ArtMiranda** [comment]
Now it works perfectly in wayland.

I edited my PicSimLab shortcut with MenuLibre and it works as it should now.

Do you have plans to upload this flatpak version on flathub?

https://user-images.githubusercontent.com/50926874/144677933-e2be3f45-a8a1-42f5-9e39-37692de54009.mp4

**Comment by lcgamboa** [comment]
Yes, there is an open issue https://github.com/lcgamboa/picsimlab/issues/49 with some fixes to make before submitting to flathub. 
I updated flatpak and disabled wayland, now it works without having to pass parameters.

**Comment by Ranjaniot** [comment]
> Apparently the Appimage format version doesn't work directly on newer Linux versions, it is necessary to specify the libgmodule library path. try: `LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgmodule-2.0.so ./PICSimLab-0.8.9-x86_64.AppImage`
> 
> I have fixed this issue in continuous build version [PICSimLab-0.8.9_211123-x86_64.AppImage](https://github.com/lcgamboa/picsimlab/releases/download/latestbuild/PICSimLab-0.8.9_211123-x86_64.AppImage) check to see if this version works for you.

![Screenshot (159)](https://github.com/lcgamboa/picsimlab/assets/142569412/25778ac5-b7ab-4f39-b98d-86f7b01c3d01)
![Screenshot (160)](https://github.com/lcgamboa/picsimlab/assets/142569412/b4e93856-048f-4947-9443-570c78194744)
helpful the embedded system design
