### ISSUE TITLE
Problem with 74xx595 block.

### ISSUE THREAD

**Issue by meyuksel** [lcgamboa/picsimlab#53]
This problem report concerns the use of two 74xx595 chips interfaced to a PIC16F628A processor in a cascaded connection. This design has been implemented on PICSimLab version 0.8.9 210727 Windows64_WX. 

I use the *Breadboard* board with a PIC16F628A processor on it. I connect a 74xx595 device to the PIC and then another  74xx595 to the first one in a *cascaded* connection. Each 74xx595 device drives 8 LEDs on their outputs. The 74xx595 device placed to the left side of the design layout is the one connected to the PIC.

- If I connect only one 74xx595 device (the one on the left side) to the PIC, everthing works normally.
- If I add the second 74xx595 device to the design, in the way I have explained above, the second device exhibits an irregular behavior.  It sometimes shows the data sent to it, and sometimes not, depending on the data.
- I have also tested the same circuit with different programs implementing various LED effects, such as 16-bit walking LED etc., and the results confirm the problem: Some of them works as expected and some do not.

I have attached a ZIP file containing a source file **hc595_demo.c** illustrating the problem. The ZIP file also contains other supporting files as well as the screen shots. Thanks and regards.

[hc595_demo.zip](https://github.com/lcgamboa/picsimlab/files/7939939/hc595_demo.zip)
.

**Comment by lcgamboa** [comment]
Hi @meyuksel, thanks for reporting the bug, it has already been fixed in the commit 0904c2dea1d206eee7ba338d3c525c55300c9e28 .
The fix of the binaries will be applied in the next version, but it can already be tested in the unstable version https://github.com/lcgamboa/picsimlab/releases/tag/latestbuild
