### ISSUE TITLE
PIC18F26K80

### ISSUE THREAD

**Issue by JASTTEWMG** [lcgamboa/picsimlab#68]
Will support for PIC18F26K80 (and similar) chips be added? Thanks

**Comment by lcgamboa** [comment]
Hi @JASTTEWMG, 

if you don't need CAN device support it is relatively simple to add support in PICSim and PICSimLab. Would this meet your need?

**Comment by malijbaly351** [comment]
Hello.
I member something...so why we can't make new programed circuit like
(Arduino,Esp32, pico,...
.)by pic family

**Comment by lcgamboa** [comment]
Hi @JASTTEWMG , 

support to PIC18F26K80 added to [unstable version.](https://github.com/lcgamboa/picsimlab/releases/tag/latestbuild)

**Comment by lcgamboa** [comment]
Added in version [0.8.12](https://github.com/lcgamboa/picsimlab/releases/tag/v0.8.12).
