### ISSUE TITLE
Load Cell & HX711 Module

### ISSUE THREAD

**Issue by RyanGee00** [lcgamboa/picsimlab#74]
Hi, can you please add Load Cell & HX711 Module configuration into PICSIMLAB? As I would lke to link the load cell to my project for further reference.
![image](https://user-images.githubusercontent.com/128585028/226848103-6b5ae446-7807-4630-b88d-b94f27b48deb.png)

**Comment by lcgamboa** [comment]
Hi @RyanGee00 ,

I've never used a Load Cell and an HX711. But from the datasheet it seems to be not very difficult to implement. I'll put it on the to-do list, and as soon as I have time I'll try to implement it.

**Comment by lcgamboa** [comment]
Hi @RyanGee00 ,
 
HX711 part added in the last unstable release https://github.com/lcgamboa/picsimlab/releases/tag/latestbuild

![Peek 26-03-2023 20-47](https://user-images.githubusercontent.com/13749258/227826930-0de75c86-4cf5-463d-8153-673417719964.gif)

**Comment by RyanGee00** [comment]
Thank you very much for that kind & quick responses!
