### ISSUE TITLE
Serial monitor is empty on sketch which writes to serial

### ISSUE THREAD

**Issue by TomasHubelbauer** [lcgamboa/picsimlab#8]
Hey, this is in follow up on buserror/simavr#345. I have this sketch:

https://github.com/TomasHubelbauer/arduino-nmea-checksum

The repository documents how to compile it to HEX and as you can see in the sketch source code, it writes into serial. When I open its HEX it picsimlab and choose the board 5 (Arduino Uno) and open the serial viewer, I don't see any output. The port selector is empty, so I cannot select one and click Open either. Is this a problem with my sketch or the order of actions I took in picsimlab?

Also, this project is beyond amazing, I wasn't even hoping there would be something like this. It's criminal that it is not more well-known. I find it crucial for people to be able to simulate Arduino sketches locally and offline, the abundance of SaaS offerings to do this doesn't work for people like me because I don't like that they require you to make an account and require you to be online to simulate.

**Comment by TomasHubelbauer** [comment]
BTW the serial doesn't work even with one of the examples you have included, the one with the pot controlling the PWM of a pin.

**Comment by lcgamboa** [comment]
Have you  made the serial configuration of com0com as described in manual? 
https://lcgamboa.github.io/picsimlab/node16.html

**Comment by TomasHubelbauer** [comment]
I missed that, now after installing it and going to File > Configure > COM1 and opening the Serial Terminal and selecting COM2 there and connecting, when I load my HEX file, I see the expected output!!! Thank you :-)
