### ISSUE TITLE
Failed to build picsimlab

### ISSUE THREAD

**Issue by omolayoabegunde** [lcgamboa/picsimlab#88]
When I tried to build the PCISimLab , here is the error i got `picsimlab4.h:30:10: fatal error:`

In file included from ppicsimlab.cc:29:
picsimlab4.h:30:10: fatal error: picsim/picsim.h: No such file or directory
   30 | #include <picsim/picsim.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by lcgamboa** [comment]
Hi @omolayoabegunde,

did you use the scripts to compile as described in the [README](https://github.com/lcgamboa/picsimlab#install-from-source)? 
PICSimLab needs several dependencies installed to compile. Using the scripts the necessary dependencies are installed before compilation.
Try the script `bscripts/build_all_and_install.sh` to compile without install dependencies in your system.

**Comment by omolayoabegunde** [comment]
Works on VMware
