### ISSUE TITLE
PICSimLab is Closing suddenly.

### ISSUE THREAD

**Issue by JorgetaHP** [lcgamboa/picsimlab#9]
I got a problem with PicSimLab 7.5. It's closing suddenly when I'm trying to use it with MPlabX.

**Comment by lcgamboa** [comment]
Which operating system and version are you using?
What version of Mplabx are you using? The latest version 5.35 is full of bugs.
If you are using windows 10, have you already tested compatibility modes? PicSimLab 7.5 apparently only works on some windows10 in compatibility mode.
Do you have any antivirus installed on your computer that blocks TCP/ IP connections between programs?

I await more information.
